---
extends: airbnb
root: true
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - config/*.js
  import/no-named-as-default: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .js
      - .jsx
  react/no-array-index-key: 0
  react/no-danger: 0
  react/no-direct-mutation-state: 1
  react/sort-comp:
    - 1
    - order:
      - static-methods
      - lifecycle
      - everything-else
      - render
  react/prop-types: 0
  arrow-parens: 0
  class-methods-use-this: 0
  comma-dangle: 0
  comma-spacing: 0
  guard-for-in: 0
  no-confusing-arrow: 0
  no-loop-func: 0
  no-param-reassign: 0
  no-plusplus: 0
  no-use-before-define: 0
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: false
  object-property-newline: 0
env:
  browser: true
  jest: true
